theme:
  error_border: "243, 139, 168" # error dialog border is Red
  error_text: "235, 160, 172" # error message text (e.g. "Spotify API reported error 404") is Maroon
  hint: "249, 226, 175" # hint text in errors Yellow
  playbar_background: "24, 24, 37" # background of progress bar "Mantle"
  playbar_progress: "86, 95, 137" # filled-in part of the progress bar Green
  playbar_progress_text: "205, 214, 244" # song length and time played/left indicator in the progress bar "Subtext 0"
  playbar_text: "205, 214, 244" # artist name in player pane is "Subtext 0"
  inactive: "108, 112, 134" # borders of inactive panes "Overlay 0"
  text: "205, 214, 244" # text in panes is "Text"
  active: "180, 249, 248" # current playing song in list Mauve
  banner: "148, 226, 213" # the "spotify-tui" banner on launch Teal
  hovered: "180, 249, 248" # hovered pane border Pink
  selected: "180, 190, 254" # a) selected pane border, b) hovered item in list, & c) track title in player Lavender
  header: "180, 190, 254" # header text in panes (e.g. 'Title', 'Artist', etc.) Lavender

behavior:
  volume_increment: 5
